export const legalStages = new Set([2, 3, 8, 28, 31, 32]);
export const stageNames = new Map([
  [2, 'FoD'],
  [3, 'PS'],
  [4, "Peach's Castle"],
  [5, 'Kongo Jungle'],
  [6, 'Brinstar'],
  [7, 'Corneria'],
  [8, 'YS'],
  [9, 'Onett'],
  [10, 'Mute City'],
  [11, 'Rainbow Cruise'],
  [12, 'Jungle Japes'],
  [13, 'Great Bay'],
  [14, 'Hyrule Temple'],
  [15, 'Brinstar Depths'],
  [16, "Yoshi's Island"],
  [17, 'Green Greens'],
  [18, 'Fourside'],
  [19, 'MKI'],
  [20, 'MKII'],
  [22, 'Venom'],
  [23, 'Poké Floats'],
  [24, 'Big Blue'],
  [25, 'Icicle Mountain'],
  [27, 'Flat Zone'],
  [28, 'DL'],
  [29, "Yoshi's Island 64"],
  [30, 'Kongo Jungle 64'],
  [31, 'BF'],
  [32, 'FD'],
]);
